### Criacao de vetores e arrays e numpy.random

In [2]:
import numpy as np 

In [2]:
lista = [1,2,3]
lista

[1, 2, 3]

In [4]:
np.array(lista) # converteu a lista em um array de python

array([1, 2, 3])

In [5]:
matriz  = [[1,2,3],[4,5,6],[7,8,9]]
matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(matriz) 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10) # criar array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
arr = np.zeros((5,5))

In [14]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
arr = np.ones((3, 3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
# criacao matriz identidade

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.linspace(0,10,2)

array([ 0., 10.])

In [21]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [100]:
np.random.rand(5) #numeros aleatorios que seguem uma distribuicao uniforme ou seja tem probabilidade igual de serem selecionados

array([0.80159045, 0.88302596, 0.49087237, 0.21223044, 0.19220681])

In [101]:
np.random.rand(5,4)

array([[0.25140027, 0.28332013, 0.50432746, 0.6707957 ],
       [0.3342469 , 0.00611267, 0.84607608, 0.22522353],
       [0.35982354, 0.01105884, 0.35507247, 0.36981922],
       [0.02300042, 0.16584144, 0.42251267, 0.29479425],
       [0.02595577, 0.16379586, 0.99795842, 0.60383757]])

In [102]:
np.random.randn(4) #distribuicao normal (mais relevnates do que a uniforme)

array([0.52965019, 0.26426511, 3.05921354, 1.51740468])

In [28]:
np.random.randint(0,100,10)

array([59, 27, 35, 20, 29, 33, 83, 10, 23, 43])

In [30]:
np.round(np.random.rand(6)*100,0)

array([37., 97., 91., 49., 90., 25.])

In [32]:
arr = np.random.rand(25)
arr

array([0.616024  , 0.01746944, 0.95920813, 0.12195968, 0.57538881,
       0.00235306, 0.79863833, 0.06217284, 0.46497332, 0.27886377,
       0.6965368 , 0.51411277, 0.91429166, 0.71571799, 0.48592235,
       0.57216108, 0.77208392, 0.87397884, 0.05363946, 0.32656477,
       0.87780464, 0.49764481, 0.58467733, 0.22724345, 0.59614079])

In [36]:
arrm = arr.reshape((5,5)) #deixou de ser um vetor de tamanho 25 e passou a ser uma matriz 5 por 5

In [37]:
arrm.shape

(5, 5)

In [39]:
arrm.max()

0.9592081278277054

In [40]:
arrm.min()

0.002353056284244648

In [42]:
arrm.argmax()

2

In [43]:
arrm.argmin()

5

### Indexacao e Fatiamento de arrays

In [76]:

array = np.arange(0,30,3)
array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [46]:
array[3]

9

In [47]:
array[2:5]

array([ 6,  9, 12])

In [49]:
array[:5] # todos os elementos ate o elemento 5

array([ 0,  3,  6,  9, 12])

In [52]:
array[2:] # todos os elementos após o elemento  de indice 2, incluso ele

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [53]:
array[2:]=100
array

array([  0,   3, 100, 100, 100, 100, 100, 100, 100, 100])

In [54]:
array = np.arange(50).reshape((5,10))
array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [55]:
array.shape

(5, 10)

In [57]:
array[:4][:] # array ate a linha 3 e todas as colunas

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [58]:
array2 = array[:3]
array2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [59]:
array2[:] = 100
array2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [60]:
array

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [61]:
array2 = array[:3].copy()

In [62]:
array

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [68]:
array[1:4,5:]

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [ 35,  36,  37,  38,  39]])

In [70]:
bool = array > 50

In [71]:
array[bool]

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100])

In [72]:
arr3 = np.linspace(0,100,30)
arr3.shape

(30,)

In [74]:
arr3 = arr3.reshape(3,10)
arr3

array([[  0.        ,   3.44827586,   6.89655172,  10.34482759,
         13.79310345,  17.24137931,  20.68965517,  24.13793103,
         27.5862069 ,  31.03448276],
       [ 34.48275862,  37.93103448,  41.37931034,  44.82758621,
         48.27586207,  51.72413793,  55.17241379,  58.62068966,
         62.06896552,  65.51724138],
       [ 68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
         82.75862069,  86.20689655,  89.65517241,  93.10344828,
         96.55172414, 100.        ]])

In [75]:
arr3[0:2,2]

array([ 6.89655172, 41.37931034])

### Operacoes com Numpy Arrays

In [77]:
ar = np.arange(0,16)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [78]:
ar + ar

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [80]:
ar - ar

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [81]:
ar * ar

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [82]:
ar / ar

C:\Users\Beatriz Almeida\AppData\Local\Temp\ipykernel_8476\1071685828.py:1: RuntimeWarning: invalid value encountered in divide
  ar / ar


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.])

In [83]:
ar ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [84]:
ar + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115])

In [85]:
ar * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000,
       1100, 1200, 1300, 1400, 1500])

In [86]:
ar - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90,
        -89,  -88,  -87,  -86,  -85])

In [87]:
ar / 100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15])

In [88]:
np.sqrt(ar)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335])

In [89]:
np.exp(ar)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06])

In [90]:
np.mean(ar)

7.5

In [91]:
np.median(ar)

7.5

In [92]:
np.std(ar)

4.6097722286464435

In [93]:
np.sin(ar)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784])

In [94]:
np.max(ar)

15

In [95]:
ar.max()

15

----

---

## Exercicios NumPy

#### Importar NumPy como np

In [96]:
import numpy as np

#### Criar matriz de 10 zeros

In [98]:
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Criar matriz de 10 ones

In [99]:
ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Criar matriz de 10 cincos


In [3]:
ones = np.ones(10) * 5
ones

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Crie um array de inteiros de 10 até 50

In [4]:
np.arange(10,51) 

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Crie um array dos numeros pares de 10 até 50

In [5]:
np.arange(10,51,2) 

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Criar matriz 3x3 com valores variando de 0 ate 8 

In [6]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Criar matriz identidade 3x3

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Usar numpy para gerar numeros aleatorios entre 0 e 1

In [9]:
np.random.rand(1)

array([0.10552761])

#### Usar numpy para gerar array de 25 numeros aleatorios tirados de uma distribuicao normal

In [10]:
np.random.randn(25)

array([-1.06283630e+00, -2.69621083e-01,  7.89181725e-01,  9.51516017e-01,
        1.75182754e+00, -2.82803804e-02,  1.21036841e+00,  4.73070584e-02,
       -1.88134364e-01, -3.47530021e-05,  1.40309980e+00, -1.48699282e-01,
       -4.10363468e-01,  1.06110847e+00, -3.84613551e-01, -1.23621344e+00,
        7.37273481e-01, -6.66951561e-01, -7.81167193e-02, -9.89682457e-01,
        4.31183322e-01,  1.26687052e+00, -3.14425391e-01, -1.30733547e+00,
        4.01309844e-01])

#### Criar a seguinte matriz 

In [11]:
np.arange(1,101) / 100

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

#### Criar um array de tamanho 20 igualmente espacado entre 0 e 1

In [12]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

### Indexação Numpy e Seleção
Agora você receberá algumas matrizes e será solicitado a replicar as saídas resultantes da matriz:

In [13]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [14]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [15]:
mat[3,-1]

20

In [16]:
mat[ : 3, 1 ].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [17]:
mat[-1, : ]

array([21, 22, 23, 24, 25])

In [18]:
mat[3: , : ]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Agora faça o seguinte

#### Obter a soma de todos os valores no "mat"

In [19]:
np.sum(mat)

325

#### Obter o desvio padrão dos valores em mat

In [ ]:
np.std(mat)

#### Obter a soma de todas as colunas em mat

In [20]:
mat.sum(axis=0)
#axis = 0 (soma das colunas)
#axis = 1 (soma das linhas)

array([55, 60, 65, 70, 75])