---

## Exercicios NumPy

#### Importar NumPy como np

In [96]:
import numpy as np

#### Criar matriz de 10 zeros

In [98]:
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Criar matriz de 10 ones

In [99]:
ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Criar matriz de 10 cincos


In [3]:
ones = np.ones(10) * 5
ones

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Crie um array de inteiros de 10 até 50

In [4]:
np.arange(10,51) 

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Crie um array dos numeros pares de 10 até 50

In [5]:
np.arange(10,51,2) 

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Criar matriz 3x3 com valores variando de 0 ate 8 

In [6]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Criar matriz identidade 3x3

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Usar numpy para gerar numeros aleatorios entre 0 e 1

In [9]:
np.random.rand(1)

array([0.10552761])

#### Usar numpy para gerar array de 25 numeros aleatorios tirados de uma distribuicao normal

In [10]:
np.random.randn(25)

array([-1.06283630e+00, -2.69621083e-01,  7.89181725e-01,  9.51516017e-01,
        1.75182754e+00, -2.82803804e-02,  1.21036841e+00,  4.73070584e-02,
       -1.88134364e-01, -3.47530021e-05,  1.40309980e+00, -1.48699282e-01,
       -4.10363468e-01,  1.06110847e+00, -3.84613551e-01, -1.23621344e+00,
        7.37273481e-01, -6.66951561e-01, -7.81167193e-02, -9.89682457e-01,
        4.31183322e-01,  1.26687052e+00, -3.14425391e-01, -1.30733547e+00,
        4.01309844e-01])

#### Criar a seguinte matriz 

In [11]:
np.arange(1,101) / 100

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

#### Criar um array de tamanho 20 igualmente espacado entre 0 e 1

In [12]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

### Indexação Numpy e Seleção
Agora você receberá algumas matrizes e será solicitado a replicar as saídas resultantes da matriz:

In [13]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [14]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [15]:
mat[3,-1]

20

In [16]:
mat[ : 3, 1 ].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [17]:
mat[-1, : ]

array([21, 22, 23, 24, 25])

In [18]:
mat[3: , : ]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Agora faça o seguinte

#### Obter a soma de todos os valores no "mat"

In [19]:
np.sum(mat)

325

#### Obter o desvio padrão dos valores em mat

In [ ]:
np.std(mat)

#### Obter a soma de todas as colunas em mat

In [20]:
mat.sum(axis=0)
#axis = 0 (soma das colunas)
#axis = 1 (soma das linhas)

array([55, 60, 65, 70, 75])